version: "3"

services:
  php-apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - sandbox
  db:
    image: postgres
    ports:
      - "8081:3306"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    networks:
      - sandbox
  adminer:
    image: adminer
    ports:
      - "8082:8080"
    networks:
      - sandbox
networks:
  sandbox:
